/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.dao.UsuarioDAO;
import model.object.Usuario;

/**
 *
 * @author Cotrim
 */
public class Cadastro extends javax.swing.JFrame {

  /**
   * Creates new form Cadastro
   */
  public Cadastro() {
    initComponents();
    this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txLogin = new javax.swing.JTextField();
    pwSenha = new javax.swing.JPasswordField();
    pwConfirmar = new javax.swing.JPasswordField();
    btCadastrar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBounds(new java.awt.Rectangle(100, 120, 150, 200));
    setMinimumSize(new java.awt.Dimension(400, 300));
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("Login");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 83, -1, -1));

    jLabel2.setText("Senha");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 124, -1, -1));

    jLabel3.setText("Confirmar senha");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 163, -1, -1));
    getContentPane().add(txLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 80, 174, -1));
    getContentPane().add(pwSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 121, 174, -1));
    getContentPane().add(pwConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 160, 174, -1));

    btCadastrar.setText("Cadastrar");
    btCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btCadastrarActionPerformed(evt);
      }
    });
    getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 211, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
    try {
      
        UsuarioDAO dao = new UsuarioDAO();
        Usuario user = new Usuario();
        user.setLogin(txLogin.getText());
        user.setSenha(pwSenha.getText());
        dao.cadastrarUsuario(user);
        JOptionPane.showMessageDialog(null, "Usuário Cadastrado");
        this.dispose();
        Login lg = new Login();
      
      
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Erro ao cadastrar usuario" + e);
    }
  }//GEN-LAST:event_btCadastrarActionPerformed

  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btCadastrar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPasswordField pwConfirmar;
  private javax.swing.JPasswordField pwSenha;
  private javax.swing.JTextField txLogin;
  // End of variables declaration//GEN-END:variables
}
